language: c
dist: trusty
addons:
  apt:
    packages: rpm
env:
  matrix:
  - OS=fedora DIST=20 FORMAT=rpm
  - OS=fedora DIST=21 FORMAT=rpm
  - OS=fedora DIST=22 FORMAT=rpm
  - OS=fedora DIST=23 FORMAT=rpm
  - OS=fedora DIST=24 FORMAT=rpm
  - OS=fedora DIST=25 FORMAT=rpm
  - OS=ubuntu DIST=trusty FORMAT=deb
  - OS=ubuntu DIST="utopic" FORMAT=deb
  - OS=ubuntu DIST="vivid" FORMAT=deb
  - OS=ubuntu DIST="wily" FORMAT=deb
  - OS=ubuntu DIST="xenial" FORMAT=deb
  - OS=ubuntu DIST="yakkety" FORMAT=deb
  - OS=ubuntu DIST="zesty" FORMAT=deb
branches:
  except: "/^v\\d/"
before_install: gem install asciidoctor fpm
install: true
script: make packages
deploy:
- provider: script
  script: 'curl --fail --data "{ \"tag_name\": \"v$(make version)\",
    \"target_commitish\": \"$TRAVIS_COMMIT\", \"name\": \"v$(make version)\"
  }" --user bot50:$GITHUB_TOKEN https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases'
  on:
    branch: master
- provider: packagecloud
  repository: libcs50
  username: cs50
  token: "${PACKAGECLOUD_TOKEN}"
  dist: "${OS}/${DIST}"
  package_glob: "*.${FORMAT}"
  skip_cleanup: true
  on:
    branch: packagecloud
notifications:
  slack:
    secure: ISOGlNSGXOrMBrKTnjTWQXVjjoBn78++xF1mUv/PYZxn3J4L4WpybLLjAuBENsD7YeHSaXUnSbIV5mDzlx5Q1cyrS+auGOHqi5xGV01zNBB1Fig1SkUf7zJS8KyjiPKyi+DexnTt1BY4xaA1uGzq9hoGZEPXKHNlz4v1I6f6fHQ=
