language: c
dist: trusty
addons:
  apt:
    packages: rpm
env:
  matrix:
  - OS=fedora DIST=20
  - OS=fedora DIST=21
  - OS=fedora DIST=22
  - OS=fedora DIST=23
  - OS=fedora DIST=24
  - OS=fedora DIST=25
  - OS=ubuntu DIST=trusty
  - OS=ubuntu DIST="utopic"
  - OS=ubuntu DIST="vivid"
  - OS=ubuntu DIST="wily"
  - OS=ubuntu DIST="xenial"
  - OS=ubuntu DIST="yakkety"
  - OS=ubuntu DIST="zesty"
branches:
  except: "/^v\\d/"
before_install: gem install asciidoctor fpm
install: true
script: make packages
deploy:
- provider: script
  script: 'curl --fail --data "{ \"tag_name\": \"v$(make version)\",
    \"target_commitish\": \"$TRAVIS_COMMIT\", \"name\": \"v$(make version)\"
  }" --user bot50:$GITHUB_TOKEN https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases'
  on:
    branch: master
- provider: packagecloud
  repository: libcs50
  username: cs50
  token: "${PACKAGECLOUD_TOKEN}"
  dist: "${OS}/${DIST}"
  skip_cleanup: true
  on:
    branch: packagecloud
notifications:
  slack:
    secure: ISOGlNSGXOrMBrKTnjTWQXVjjoBn78++xF1mUv/PYZxn3J4L4WpybLLjAuBENsD7YeHSaXUnSbIV5mDzlx5Q1cyrS+auGOHqi5xGV01zNBB1Fig1SkUf7zJS8KyjiPKyi+DexnTt1BY4xaA1uGzq9hoGZEPXKHNlz4v1I6f6fHQ=
