language: c
dist: trusty
env:
  global: OS=ubuntu
  matrix:
  - DIST="trusty"
  - DIST="utopic"
  - DIST="vivid" 
  - DIST="wily"
  - DIST="xenial"
  - DIST="yakkety"
  - DIST="zesty"
branches:
  except: "/^v\\d/"
before_install: gem install asciidoctor fpm
install: true
script: make deb
deploy:
- provider: script
  script: 'curl --fail --data "{ \"tag_name\": \"v$(make version)\",
    \"target_commitish\": \"$TRAVIS_COMMIT\", \"name\": \"v$(make version)\"
  }" --user bot50:$GITHUB_TOKEN https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases'
  on:
    branch: master
- provider: packagecloud
  repository: libcs50
  username: cs50
  token: "${PACKAGECLOUD_TOKEN}"
  dist: "${OS}/${DIST}"
  skip_cleanup: true
  on:
    branch: packagecloud
notifications:
  slack:
    secure: ISOGlNSGXOrMBrKTnjTWQXVjjoBn78++xF1mUv/PYZxn3J4L4WpybLLjAuBENsD7YeHSaXUnSbIV5mDzlx5Q1cyrS+auGOHqi5xGV01zNBB1Fig1SkUf7zJS8KyjiPKyi+DexnTt1BY4xaA1uGzq9hoGZEPXKHNlz4v1I6f6fHQ=
