dist: trusty
branches:
  except: "/^v\\d/"
before_install: gem install asciidoctor fpm
install: true
script: make deb
deploy:
- provider: script
  script: 'curl --fail --data "{ \"tag_name\": \"v$(make version)\",
    \"target_commitish\": \"$TRAVIS_COMMIT\", \"name\": \"v$(make version)\"
  }" --user bot50:$GITHUB_TOKEN https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases'
  on:
    branch: master
- provider: packagecloud
  username: cs50
  repository: libcs50
  dist:
  - "ubuntu/precise"
  - "ubuntu/trusty"
  - "ubuntu/utopic"
  - "ubuntu/vivid"
  - "ubuntu/wily"
  - "ubuntu/xenial"
  - "ubuntu/yakkety"
  - "ubuntu/zesty"
  token: "${PACKAGECLOUD_TOKEN}"
  package_glob: "*.deb"
  skip_cleanup: true
  on:
    branch: packagecloud
notifications:
  slack:
    secure: ISOGlNSGXOrMBrKTnjTWQXVjjoBn78++xF1mUv/PYZxn3J4L4WpybLLjAuBENsD7YeHSaXUnSbIV5mDzlx5Q1cyrS+auGOHqi5xGV01zNBB1Fig1SkUf7zJS8KyjiPKyi+DexnTt1BY4xaA1uGzq9hoGZEPXKHNlz4v1I6f6fHQ=
